### ISSUE TITLE
Total adjustments greater than total loss

### ISSUE THREAD

**Issue by fberger** [adlr/wash-sale-calculator#7] opened 2015-04-02 14:27 UTC
I have input that generates adjustments that are greater than the total loss, this can't be correct, can it?

What's a good way to debug this?

Thanks,
Felix

**Comment by adlr** [comment] 2015-04-03 15:20
The code isn't that big, so you could look into it yourself.

Also, if you can generate a minimal example of what you think the issue is, I can take a look.

Keep in mind that I'm no tax expert/CPA and I will assuredly make mistakes.

**Comment by fberger** [comment] 2015-04-04 13:35
Thanks for the quick reply and writing this great tool, Andrew.

I think I identified the issue. I have multiple short-term sales (acquired less than 30 days before sale) on the same day from different lots which are then used as replacements for each other. If I mark these as IsReplacement = True, they won't be used.

At this point I don't understand the IRS rules well enough to know what the definition of a lot is and whether securities sold on the same day can ever be used as replacements.

In the code I found the following comment:

def buy_lots_within_window(lots, loss):
  # Returns an array of lots that were bought within 30 days of the loss,
  # but were not sold on this date

but the code doesn't look at the sale date and instead just looks at whether a lot is marked as replacement or not. Would it make sense to modify this and also compare the sale dates and make sure they're not the same?

Cheers,
Felix

**Comment by adlr** [comment] 2015-04-04 15:06
I used to be under the impression that you can't pair up shares that were sold on the same day (which is where that now outdated comment came from). That impression came from IRS pub 550, which says "Loss and gain on same day. Loss from a wash sale of one block of stock or securities cannot be used to reduce any gains on identical blocks sold the same day." However, after reviewing some Fairmark web pages (and trusting them b/c they sound intelligent), I changed my mind. Specifically, that was based on http://fairmark.com/capgain/wash/wssameday.htm "you have to treat separate blocks of stock separately, even if you sell them all on the same day."

There seems to be an unwritten rule that the replacement shares can't be sold on or before the time when the original shares were sold. This code should probably be updated to reflect that.

I think we may want logic like this, so that we can handle the case of the same-day sales that do apply from the Fairmark article above:

```
Assume LotA is a loss that will be paired with LotB.
If LotB was sold on a date after LotA was sold, permit the pairing.
If LotB was sold on a date before LotA was sold, disallow pairing.
If you get here, LotA and LotB were sold on the same day. Permit pairing iff LotB was bought on the same day LotB was sold
```

I haven't implemented this, but it seems like it could work. Do you want to try and if it works, submit a pull request?

The thing I will mention is that, afaik, neither of the two committers in this project used it for their own taxes this year.

**Comment by fberger** [comment] 2015-04-04 17:37
Thanks, this seems to work, I modified the function `buy_lots_within_window` as follows:

```
def buy_lots_within_window(lots, loss):
  def match(lot, loss):
    if abs((lot.buydate - loss.selldate).days) > 30:
      return False
    if buy_lots_match(lot, loss):
      return False
    if lot.is_replacement:
      return False
    if not lot.selldate or lot.selldate > loss.selldate:
      return True
    if lot.selldate < loss.selldate:
      return False
    #  lot.selldate == loss.selldate
    if lot.buydate == lot.selldate:
      return True
  return [lot for lot in lots if match(lot, loss)]
```

I will submit a patch with a test case next week.

**Comment by adlr** [comment] 2015-04-13 23:06
Marking as closed since the patch went in. Please let me know if this a mistake.

**Comment by bbreslauer** [comment] 2016-03-21 07:22
Hi,

I've been using this script to compare its output against my 1099-B, and I think that the fix for this issue is slightly wrong. Specifically that this check shouldn't exist:

```
if lot.buydate == lot.selldate:
      return True
```

The reason I think this is that the "Loss and gain on same day" example, and the Fairmark overview, IMO are trying to point out that if you sell a bunch of stock, that was acquired >30 days ago, on the same day, then you can't just combine all the sales together to get one value for the gain or loss. You need to track the gain or loss individually for each lot.

But this doesn't preclude such a loss from washing with another purchase within the 30 days. For instance, if you buy 10 shares on day N, another 10 shares on day N+10, and sell all the shares on day N+20 (and each lot has a loss), then the first 10 shares should be a disallowed loss, and added to the cost basis of the second 10 shares.

What do you think? Am I misunderstanding something here (acknowledging the fact that none of us are CPAs)?

**Comment by adlr** [comment] 2016-03-21 15:32
bbreslauer, I find it hard to reason about these things in English sometimes. Would you be able to create a test in the style of the others that illustrates why we need to take that line out? Also, does taking that out break any of the existing tests? If so, how can we prevent those from breaking?

Thanks,
-adlr

**Comment by bbreslauer** [comment] 2016-03-22 04:41
Sorry if I wasn't clear. Here's a test that shows what I'm talking about:

Input:
Cnt,Sym,Desc,BuyDate,Basis,SellDate,Proceeds,AdjCode,Adj,FormPosition,BuyLot,IsReplacement
10,GOOG,A,9/15/2014,2000,10/5/2014,1800,,,lot1
10,GOOG,B,9/25/2014,1900,10/5/2014,1800,,,lot2

Output:
Cnt,Sym,Desc,BuyDate,Basis,SellDate,Proceeds,AdjCode,Adj,FormPosition,BuyLot,IsReplacement
10,GOOG,B,09/05/2014,2100.0,10/05/2014,1800.0,,0.0,lot2,"2,1",True
10,GOOG,A,09/15/2014,2000.0,10/05/2014,1800.0,W,200.0,lot1,1,

I think instead of the check I mentioned, the match function should just "return True" at the end (instead of implicitly returning None).

The only test that breaks is the same_day_sold_not_replacement.csv one, which was added with the previous fix (and I believe is legitimately wrong due to this issue).

**Comment by adlr** [comment] 2016-03-22 16:00
bbreslauer, I think you are right. fberger, you submitted in the test case that we think may be wrong. Do you have any comment about this? Do you have some information (e.g. Schwab 1099Bs) that match your test case?

**Comment by adlr** [comment] 2016-03-25 04:34
Marking closed after taking pull request from bbreslauer. Felix Berger is currently unable to comment on his previous code, but hopefully he can comment when he has time.

**Closed as completed by adlr** 2016-03-25 04:34 UTC
